---
image: dokku/ci-docker-image

stages:
  - build
  - deploy

variables:
  GIT_DEPTH: 0

build:
  stage: build
  only:
    - master
  script: |
    # build the image
    docker build -t "$CI_PROJECT_PATH_SLUG:$CI_COMMIT_SHA" .

    # login to docker hub
    echo "$DOCKERHUB_TOKEN" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin

    # push the image
    docker push "$CI_PROJECT_PATH_SLUG:$CI_COMMIT_SHA"

deploy:
  stage: deploy
  only:
    - master
  variables:
    GIT_REMOTE_URL: ssh://dokku@dokku.me:22/appname
  script: |
    DEPLOY_DOCKER_IMAGE "$CI_PROJECT_PATH_SLUG:$CI_COMMIT_SHA" dokku-deploy
  after_script: [dokku-unlock]
