---
image: dokku/ci-docker-image

stages:
  - deploy

variables:
  GIT_DEPTH: 0

deploy:
  stage: deploy
  only:
    - master
  variables:
    # specify the `main` branch as the remote branch to push to
    BRANCH: main
    GIT_REMOTE_URL: ssh://dokku@dokku.me:22/appname
  script: dokku-deploy
  after_script: [dokku-unlock]
