---
image: dokku/ci-docker-image

stages:
  - deploy

deploy:
  stage: deploy
  only:
    - master
  variables:
    GIT_REMOTE_URL: ssh://dokku@dokku.me:22/appname
  script: dokku-deploy
  after_script: dokku-unlock
