---
image: dokku/ci-docker-image

stages:
  - deploy

variables:
  GIT_DEPTH: 0

deploy:
  stage: deploy
  only:
    - main
  variables:
    GIT_REMOTE_URL: ssh://dokku@dokku.me:22/appname
    # specify an alternative ssh host key
    SSH_HOST_KEY: $SOME_SSH_HOST_KEY
  script: dokku-deploy
  after_script: [dokku-unlock]
